compatibility_date = "2025-06-07"
main = "build/worker/shim.mjs"
name = "${PROJECT_NAME}"

workers_dev = false
preview_urls = true

[build]
command = "worker-build --release --no-default-features --features preview"

[assets]
binding = "ASSETS"
directory = "./public/"

[observability.logs]
enabled = true
